### ISSUE TITLE
Cute animation for favorite session

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#151]
## Overview (Required)
- 🔖 
![image](https://user-images.githubusercontent.com/1386930/50725207-84c9b680-113d-11e9-8afa-6fa45580d5e4.png)

**Comment by yumemi-hkusu** [comment]
It seems possible, writing as follows in `SessionDetailFragment.kt`.

```
binding.sessionFavorite.setOnClickListener {
    val session = binding.session ?: return@setOnClickListener

    it.scaleX = 0.5f
    it.scaleY = 0.5f
    it.animate().scaleX(1.0f).scaleY(1.0f).setDuration(300)
        .interpolator = OvershootInterpolator()

    sessionContentsActionCreator.toggleFavorite(session)
}
```

<img src="https://user-images.githubusercontent.com/44076858/50906232-ff5d4380-1467-11e9-8631-740744e7efc2.gif" width="300">

(Sorry, I can do it because busy)

If possible, It may be nice to solve the time lag until it is reflected.

**Comment by takahirom** [comment]
Nice and simple animation!🔖
Do you want to implement it? I will assign you.

**Comment by yumemi-hkusu** [comment]
Sorry, I can do it because busy.. ( I have to make a session slide..  )
