### ISSUE TITLE
Fix category tags are displayed in previous languages when switching languages from system settings

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#187]
## Overview (Required)
- Actually, after starting the application in Japanese setting, changing it to English will be like this

### Session
![session](https://user-images.githubusercontent.com/5106629/50737682-8f548080-120f-11e9-979a-b8285837193a.png)

### Filter
![filter](https://user-images.githubusercontent.com/5106629/50737686-97acbb80-120f-11e9-9bec-3241a5a2e4a5.png)

**Comment by gen0083** [comment]
In order to solve this problem, I think it is necessary to listen to ACTION_LOCALE_CHANGE broadcast.
This will also be necessary to set up NotificationChannel in the future.
However, since I am not familiar with multi-module manners, I do not know where is better to place the BroadcastReceiver.

- feature/system (because it relates to the system)
- frontend/android (because it is about android)
- or other place

Can you give me advice?

**Comment by takahirom** [comment]
Thank you for a question!
I think we can listen to ACTION_LOCALE_CHANGE broadcast in SystemActionCreator. 
And If you call `dispatcher.launchAndDispatch(Action.SystemPropertyLoaded(systemProperty))`
Languages are applied. 
https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/SystemActionCreator.kt#L19
If we listen `SystemStore.systemProperty LiveData` or use `systemStore.lang`
https://github.com/DroidKaigi/conference-app-2019/blob/master/frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt#L32

**Comment by takahirom** [comment]
Probably we should use something about lifecycle for that. 
I think that lifecycle may be passed to ActionCreator if necessary.

**Comment by gen0083** [comment]
You open my eyes!
I was thinking that I had to implement BroadcastReceiver.
I'll try it.
