### ISSUE TITLE
Prepare Xcode project file using Kotlin Multi Platform

### ISSUE THREAD

**Issue by kikuchy** [DroidKaigi/conference-app-2019#389]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- In order to achieve #132 , we need Xcode project to build iOS application.
- Maybe appropriate place of project files is in `frontend/ios` .
- This Xcode project uses Kotlin Multiplatform modules under `:data` , and will write other sources codes in Swift (Maybe it's hard to implement each screen like `:feature` modules in Kotlin Multiplatform modules...)
    - All ViewControllers are in single Xcode project.
    - We can use Cocoapods and Carthage as package manager.

**Comment by takahirom** [comment]
I created the same issue. But it will close #384

* At first I think that an empty screen is good. Because we can develop frontend while developing each module of data.So **you should not implement anything like the session list. Just show an empty screen!**
* Please be able to call model module classes from frontend / ios

**Comment by takahirom** [comment]
> I'm creating base of Xcode project.

Sorry, Can I assign you? 😅
